version: '3'
services:
  kaldi-ru:
    image: alphacep/kaldi-ru:latest
    env_file:
      - .env
    ports:
      - ${PORT_RU}:2700
  kaldi-en:
    image: alphacep/kaldi-en:latest
    env_file:
      - .env
    ports:
      - ${PORT_EN}:2700